# Generated by Django 5.1.4 on 2024-12-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tresdos_agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseagent',
            name='parent_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='midagent',
            name='parent_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
