# Generated by Django 5.1.4 on 2024-12-26 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tresdos_agents', '0002_baseagent_parent_percentage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='AgentIncomeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=100)),
                ('agent_role', models.CharField(max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('percentage', models.IntegerField()),
                ('parent_percentage', models.IntegerField(default=0)),
                ('income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('report_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tresdos_agents.reportdate')),
            ],
        ),
    ]
