# Generated by Django 5.1.4 on 2025-01-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tresdos_agents', '0003_reportdate_agentincomereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentincomereport',
            name='agent_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
